### ISSUE TITLE
Space after keywords: return

### ISSUE THREAD

**Issue by danistefanovic** [infektweb/eslint-config-infektweb#17]
```js
return(
    // ...
);
```

vs.

```js
return (
    // ...
);
```

Scheint derzeit von [space-after-keywords](http://eslint.org/docs/rules/space-after-keywords) nicht unterstützt zu werden

**Comment by christianharke** [comment]
Mit der [v2.0.0-beta.1](https://github.com/eslint/eslint/releases/tag/v2.0.0-beta.1) von Eslint kommt eine Rule `keyword-spacing`, die auch return unterstützt.

=> Abwarten oder auf Beta upgraden?

**Comment by danistefanovic** [comment]
Abwarten

**Comment by christianharke** [comment]
Wurde bereits via PR https://github.com/infektweb/eslint-config-infektweb/pull/31 umgesetzt.
