### ISSUE TITLE
npm version: automatically push commit and tag

### ISSUE THREAD

**Issue by christianharke** [infektweb/eslint-config-infektweb#28]
Wie in der npm help beschrieben, im postversion Script auf Git pushen:
```json
"scripts": {
  "version": "git add -A",
  "postversion": "git push && git push --tags"
}
```

**Comment by danistefanovic** [comment]
* :+1:  für `postversion`
* bei  `git add` bin ich mir nicht sicher. `git add` alleine bringt nicht viel ohne `git commit`
