### ISSUE TITLE
Bug with react/forbid-prop-types

### ISSUE THREAD

**Issue by danistefanovic** [infektweb/eslint-config-infektweb#8]
```
    "plugins": [
        "react"
    ],
    "rules": {
        "react/forbid-prop-types": 1,
    }
```

```
c:\workspace\guidelines.web\node_modules\eslint-plugin-react\lib\rules\forbid-prop-types.js:71
      if (isForbidden(declaration.value.property.name)) {
                                                ^
TypeError: Cannot read property 'name' of undefined
    at c:\workspace\guidelines.web\node_modules\eslint-plugin-react\lib\rules\forbid-prop-types.js:71:49
```

**Comment by christianharke** [comment]
Der Bug wurde zwischenzeitlich behoben https://github.com/yannickcr/eslint-plugin-react/issues/230

Aktuell crasht ESlint mit dieser Rule noch immer, wegen den propTypes in
https://github.com/infektweb/guidelines.v4/blob/master/web/app/modules/reader/components/SearchResultList/SearchResultItem/SearchResultItemDetails/SearchResultItemDetails.js#L14-L17

Dies wurde aber im Branch fix-forbid-prop-types-linting-errors behoben
https://github.com/infektweb/guidelines.v4/blob/fix-forbid-prop-types-linting-errors/web/app/modules/reader/components/SearchResultList/SearchResultItem/SearchResultItemDetails/SearchResultItemDetails.js#L14
